server {
    listen 80;
    server_name 13.60.33.241;

    client_max_body_size 100M;

    location /api/files/upload {
        proxy_pass http://backend:5000;
    }

    location /api/ {
        proxy_pass http://backend:5000;
    }

    location /uploads/ {
        proxy_pass http://backend:5000;
    }

    location / {
        proxy_pass http://frontend:3000;
    }

    location /health {
        proxy_pass http://backend:5000/api/health;
    }
}
